# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15920ad699f79314af95a8fb5ee5f58ae90adf1406f5815b7cafecc2f53c51f55dfdab9c11a779e37b6917195d113d536bf2ed7122f5a62615bc5a11cf8894bb

test:
  secret_key_base: 7aadf5cfc36a343a38bdba897ea21b193c0473270d8a02870c8b18d63c84d986119c80434946a5c53098681a2c96c7fe584ede19f97ec3bbbae50970b58e780f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
